services:
  sequencer:
    image: ghcr.io/espressosystems/espresso-sequencer/sequencer:20260825
    stop_grace_period: 15m
    entrypoint:
      - tini
      - -g
      - --
    command:
      - /bin/sequencer-sqlite
      - --
      - storage-sql
      - --
      - http
      - --
      - catchup
      - --
      - config
      - --
      - explorer
      - --
      - light-client
      - --
      - query
      - --
      - status
    environment:
      - RUST_LOG=warn,hotshot_libp2p_networking=off
      #- RUST_LOG_FORMAT=json
      #- ESPRESSO_NODE_IS_DA=true
      - ESPRESSO_NODE_API_PORT=8088
      - ESPRESSO_NODE_GENESIS_FILE=/genesis/decaf.toml
      - ESPRESSO_NODE_API_PEERS=https://cache.decaf.testnet.espresso.network/,https://query.decaf.testnet.espresso.network/
      - ESPRESSO_NODE_CONFIG_PEERS=https://cache.decaf.testnet.espresso.network/,https://query.decaf.testnet.espresso.network/
      - ESPRESSO_NODE_STATE_PEERS=https://cache.decaf.testnet.espresso.network/,https://query.decaf.testnet.espresso.network/
      - ESPRESSO_STATE_RELAY_SERVER_URL=https://state-relay.decaf.testnet.espresso.network
      - ESPRESSO_NODE_CDN_ENDPOINT=cdn.decaf.testnet.espresso.network:1737
      #
      # Error and node telemetry reporting (optional)
      #
      - ESPRESSO_NODE_TELEMETRY_LOGS_ENABLE=true
      - ESPRESSO_NODE_TELEMETRY_METRICS_ENABLE=true
      #
      # Libp2p
      #
      - ESPRESSO_NODE_LIBP2P_BIND_ADDRESS=0.0.0.0:4455
      - ESPRESSO_NODE_LIBP2P_ADVERTISE_ADDRESS=${PUBLIC_IP:?error}:4455
      - ESPRESSO_NODE_LIBP2P_BOOTSTRAP_NODES=/dns/decaf-network-5dfb61bd543bfdd3.elb.us-east-2.amazonaws.com/udp/2004/quic-v1/p2p/12D3KooWNg4QuisuNS7Vygd1Yv6ywebT88uzD3q7PtiWxLiUura8,/dns/decaf-network-5dfb61bd543bfdd3.elb.us-east-2.amazonaws.com/udp/2005/quic-v1/p2p/12D3KooWJnHafr5U6qCdJ5MqS6U9NaoS2LDEVar7jaQvbwXzt4vx,/dns/decaf-network-5dfb61bd543bfdd3.elb.us-east-2.amazonaws.com/udp/2006/quic-v1/p2p/12D3KooWR9xFqHYgz4pBxCzCAFCdDcczJKqhFgwC1wg8yRZiy8Ft,/dns/decaf-network-5dfb61bd543bfdd3.elb.us-east-2.amazonaws.com/udp/2007/quic-v1/p2p/12D3KooWP1XCQPYWn5vT7euC48aDsbuiG8869ky3ANCNmCvfVvTa,/dns/decaf-network-5dfb61bd543bfdd3.elb.us-east-2.amazonaws.com/udp/2008/quic-v1/p2p/12D3KooWHtayvhWKfCnW6cuyMTknwGmVvm1fbQTSoyythpQQpWuW
      #
      # Cliquenet
      #
      - ESPRESSO_NODE_CLIQUENET_BIND_ADDRESS=0.0.0.0:9977
      - ESPRESSO_NODE_CLIQUENET_ADVERTISE_ADDRESS=${PUBLIC_IP:?error}:9977
      #
      # SQLite
      #
      - ESPRESSO_NODE_EMBEDDED_DB=true
      #
      # Pruning
      #
      #- ESPRESSO_NODE_DATABASE_PRUNE=true
      #- ESPRESSO_NODE_POSTGRES_PRUNE=true
      #- ESPRESSO_NODE_PRUNER_PRUNING_THRESHOLD=10GB
      #- ESPRESSO_NODE_PRUNER_MINIMUM_RETENTION=1d
      #- ESPRESSO_NODE_PRUNER_TARGET_RETENTION=7d
      #- ESPRESSO_NODE_PRUNER_MAX_USAGE=8000
      #- ESPRESSO_NODE_PRUNER_INTERVAL=5m
      #
      # Secrets
      #
      - ESPRESSO_L1_PROVIDER=${ESPRESSO_NODE_L1_PROVIDER:?error}
      - ESPRESSO_L1_WS_PROVIDER=${ESPRESSO_NODE_L1_WS_PROVIDER:?error}
      # New mnemonic to so we only need one secret
      - ESPRESSO_NODE_KEY_MNEMONIC=${ESPRESSO_NODE_KEY_MNEMONIC:?error}
      #
      # Old pre-mnemonic manual key process
      #
      #- ESPRESSO_NODE_PRIVATE_STAKING_KEY=${ESPRESSO_NODE_PRIVATE_STAKING_KEY:?error}
      #- ESPRESSO_NODE_PRIVATE_STATE_KEY=${ESPRESSO_NODE_PRIVATE_STATE_KEY:?error}
      #- ESPRESSO_NODE_PRIVATE_X25519_KEY=${ESPRESSO_NODE_PRIVATE_X25519_KEY:?error}
      #
      # Optional Node Identification
      #
      #- ESPRESSO_NODE_IDENTITY_NODE_NAME=Our-Node-1
      #- ESPRESSO_NODE_IDENTITY_COMPANY_NAME=Example Company
      #- ESPRESSO_NODE_IDENTITY_COMPANY_WEBSITE=https://example.com
      #- ESPRESSO_NODE_IDENTITY_OPERATING_SYSTEM=Linux
      #- ESPRESSO_NODE_IDENTITY_NETWORK_TYPE=AWS
      #- ESPRESSO_NODE_IDENTITY_COUNTRY_CODE=US
      #- ESPRESSO_NODE_IDENTITY_LATITUDE=0.0
      #- ESPRESSO_NODE_IDENTITY_LONGITUDE=0.0
    ports:
      - 8088:8088 # General HTTP
      - 4455:4455/tcp # Libp2p
      - 4455:4455/udp # Libp2p
      - 9977:9977/tcp # Cliquenet
    volumes:
      - ./datastore:/store/sequencer
